FROM mcr.microsoft.com/mssql/server:2019-latest

# Copy the entrypoint script into the container
COPY docker-entrypoint.sh /usr/src/app/docker-entrypoint.sh

# Run the entrypoint script
ENTRYPOINT ["/usr/src/app/docker-entrypoint.sh"]
